window.KK_DATA = {
  works: [
    { id: 1,  title: "Singe I",     src: "img/SINGE/SINGE 1.jpeg",      status: "sold" },
    { id: 2,  title: "Singe II",    src: "img/SINGE/SINGE 2.jpeg",      status: "sold" },
    { id: 3,  title: "Singe III",   src: "img/SINGE/SINGE 3.jpeg",      status: "sold" },
    { id: 4,  title: "Bob",         src: "img/SINGE/SINGE - BOB.jpeg",  status: "sold" },
    { id: 5,  title: "Singe VII",   src: "img/SINGE/SINGE 7.jpeg",      status: "sold" },
    { id: 6,  title: "Singe VIII",  src: "img/SINGE/SINGE 8.jpeg",      status: "sold" },
    { id: 7,  title: "Singe IX",    src: "img/SINGE/SINGE 9.jpeg",      status: "sold" },
    { id: 8,  title: "Singe X",     src: "img/SINGE/SINGE 10.jpeg",     status: "sold" },
    { id: 9,  title: "Singe XII",   src: "img/SINGE/SINGE 12.jpeg",     status: "sold" },
    { id: 10, title: "Singe XIII",  src: "img/SINGE/SINGE 13.jpeg",     status: "sold" },
    { id: 11, title: "Singe XIV",   src: "img/SINGE/SINGE - 14.jpeg",   status: "sold" },
    { id: 12, title: "Singe XV",    src: "img/SINGE/SINGE - 15.jpeg",   status: "sold" },
    { id: 13, title: "Singe XVI",   src: "img/SINGE/SINGE - 16.jpeg",   status: "sold" },
    { id: 14, title: "Singe XVII",  src: "img/SINGE/SINGE - 17.jpeg",   status: "sold" },
    { id: 15, title: "Singe XVIII", src: "img/SINGE/SINGE - 18.jpeg",   status: "sold" },
    { id: 16, title: "Singe XIX",   src: "img/SINGE/SINGE - 19.jpeg",   status: "sold" },
    { id: 17, title: "Singe XX",    src: "img/SINGE/SINGE - 20.jpeg",   status: "sold" },
    { id: 18, title: "Singe XXI",   src: "img/SINGE/SINGE - 21.jpeg",   status: "sold" },
    { id: 19, title: "Tutu",        src: "img/SINGE/SINGE - TUTU.jpeg", status: "sold" },
    { id: 20, title: "Singe",       src: "img/SINGE/SINGE.jpeg",        status: "sold" },
  ],
  heroImg:   "img/kai-homepage.jpg",
  aboutImg:  "img/back-profil.jpg",
  humainImg: "img/SINGE/SINGE - BOB.jpeg",
};

window.KK_I18N = {
  fr: {
    navCollection: "Collection", navHumain: "Humain", navAbout: "L'Artiste",
    navEngagement: "Engagement", navPress: "Presse", btnContact: "Contact Galerie",
    heroEyebrow: "Artiste contemporain · Paris · Depuis 2024",
    heroLead: "L'encre comme geste primitif. Le primate comme miroir de l'homme.",
    heroStat1Label: "Collection I", heroStat1Val: "Singe — complète",
    heroStat2Label: "Œuvres originales", heroStat2Val: "21",
    heroStat3Label: "Médium", heroStat3Val: "Encre de Chine",
    heroTag: "Atelier · Paris 2024",
    marquee: "Collection Singe · Encre de Chine · Œuvres originales · Éditions limitées · Art engagé · AIDE Fédération — ONU ·",
    collectionEyebrow: "Collection I — 2024", collectionTitle: "Singe",
    collectionMeta: "Une série de 21 portraits à l'encre de Chine brut. Chaque trait naît d'un geste libre, sans repentir. Le primate — choisi pour sa « brute humanité » — devient le prétexte à un miroir tendu sur notre propre condition.",
    sold: "Vendu", worksCaption: "Encre de Chine · Original",
    humainEyebrow: "Collection II · En gestation", humainTitle: "Humain",
    humainStatus: "En cours de création",
    humainLead: "Après le primate, l'homme. Une nouvelle série en gestation — mêmes gestes libres, même encre brute. Explorer les failles et les lumières de la condition humaine.",
    humainNotify: "Être prévenu·e de la sortie",
    aboutEyebrow: "L'Artiste", aboutTitle: "Une trajectoire", aboutTitleEm: "hors du commun",
    aboutMeta: "Du Vietnam à Paris, de Publicis à l'encre de Chine — une vie au croisement des humanités.",
    aboutP1: "Né au Vietnam, orphelin, arrivé en France en bas âge. Élevé par plusieurs familles aux traditions plurielles — ivoirienne, musulmane, bouddhiste, chrétienne — Kai Krill a forgé sa vision à l'intersection de toutes les humanités.",
    aboutP2: "Diplômé de l'École Boulle (MANAA) et titulaire d'un Bachelor of Arts de Middlesex University, il exerce d'abord comme Directeur Créatif chez Publicis, avant de créer ses propres sociétés — qu'il revend pour se consacrer entièrement à l'art et à l'action humanitaire.",
    aboutP3: "L'art revient dans sa vie par un défi : dessiner un singe à l'encre de Chine par jour, pendant 30 jours, à la demande de son fils. De ce geste naît une œuvre. De cette œuvre, une mission.",
    quote: "Le primate ne ment pas. Son regard porte ce que l'homme cherche à dissimuler.",
    cvLabel: "Parcours",
    engagementEyebrow: "Engagement", engagementTitle: "L'art comme", engagementTitleEm: "acte politique",
    engagementP1: "Kai Krill reverse 70 % de l'intégralité des fonds générés à l'AIDE Fédération, ONG dotée du statut consultatif auprès des Nations Unies. Chaque œuvre acquise finance directement des projets humanitaires concrets, sur le terrain.",
    engagementP2: "L'esthétique et l'activisme ne s'opposent pas — ils se nourrissent l'un l'autre. Posséder une œuvre de Kai Krill, c'est participer à une action dans le monde réel.",
    impact70Lbl: "des fonds reversés à l'AIDE Fédération, à chaque vente",
    impactUNLbl: "Statut consultatif auprès des Nations Unies",
    impact30Lbl: "Un singe par jour — le geste fondateur",
    impact2Lbl: "Collections — Singe (complète) & Humain (à venir)",
    pressEyebrow: "Mentions",
    contactEyebrow: "Galeries & Collectionneurs", contactTitle: "Prendre", contactTitleEm: "Contact",
    contactLead: "Pour toute demande d'acquisition, proposition d'exposition ou partenariat galerie.",
    contactL1: "Acquisitions — originaux et éditions limitées",
    contactL2: "Propositions d'exposition — France & international",
    contactL3: "Partenariats galerie — demande sur dossier",
    contactL4: "Presse & médias — dossier artistique disponible",
    fFirstname: "Prénom", fLastname: "Nom", fEmail: "Adresse email",
    fStructure: "Structure / Galerie", fSubject: "Nature de la demande", fMessage: "Message",
    fSubmit: "Envoyer la demande",
    footRights: "© 2024 Kai Krill — Tous droits réservés",
    footShip: "Œuvres produites et expédiées depuis la France",
  },
  en: {
    navCollection: "Collection", navHumain: "Human", navAbout: "The Artist",
    navEngagement: "Commitment", navPress: "Press", btnContact: "Gallery Enquiries",
    heroEyebrow: "Contemporary artist · Paris · Since 2024",
    heroLead: "Ink as a primal gesture. The primate as a mirror of man.",
    heroStat1Label: "Collection I", heroStat1Val: "Singe — complete",
    heroStat2Label: "Original works", heroStat2Val: "21",
    heroStat3Label: "Medium", heroStat3Val: "Indian ink",
    heroTag: "Studio · Paris 2024",
    marquee: "Singe Collection · Indian Ink · Original Works · Limited Editions · Engaged Art · AIDE Federation — UN ·",
    collectionEyebrow: "Collection I — 2024", collectionTitle: "Singe",
    collectionMeta: "A series of 21 portraits in raw Indian ink. Each line is a free gesture, without repentance. The primate — chosen for its \"raw humanity\" — becomes a mirror held up to our own condition.",
    sold: "Sold", worksCaption: "Indian ink · Original",
    humainEyebrow: "Collection II · In progress", humainTitle: "Human",
    humainStatus: "Work in progress",
    humainLead: "After the primate, man. A new series in gestation — same free gestures, same raw ink. Exploring the cracks and the lights of the human condition.",
    humainNotify: "Get notified at release",
    aboutEyebrow: "The Artist", aboutTitle: "An uncommon", aboutTitleEm: "trajectory",
    aboutMeta: "From Vietnam to Paris, from Publicis to Indian ink — a life at the crossroads of humanity.",
    aboutP1: "Born in Vietnam, orphaned, arrived in France at a young age. Raised by several families of plural traditions — Ivorian, Muslim, Buddhist, Christian — Kai Krill forged his vision at the intersection of all humanities.",
    aboutP2: "A graduate of École Boulle (MANAA) and holder of a Bachelor of Arts from Middlesex University, he first worked as Creative Director at Publicis before founding his own companies — which he sold to devote himself entirely to art and humanitarian action.",
    aboutP3: "Art returned to his life through a challenge: to draw one monkey in Indian ink every day, for 30 days, at his son's request. From that gesture, a body of work was born. From that work, a mission.",
    quote: "The primate does not lie. Its gaze carries what man seeks to conceal.",
    cvLabel: "Biography",
    engagementEyebrow: "Commitment", engagementTitle: "Art as", engagementTitleEm: "political act",
    engagementP1: "Kai Krill donates 70% of all funds generated to AIDE Fédération, an NGO with consultative status at the United Nations. Each acquired work directly finances concrete humanitarian projects in the field.",
    engagementP2: "Aesthetics and activism do not oppose each other — they feed one another. To own a work by Kai Krill is to participate in an action in the real world.",
    impact70Lbl: "of funds donated to AIDE Fédération, on every sale",
    impactUNLbl: "Consultative status at the United Nations",
    impact30Lbl: "One monkey a day — the founding gesture",
    impact2Lbl: "Collections — Singe (complete) & Human (forthcoming)",
    pressEyebrow: "Mentions",
    contactEyebrow: "Galleries & Collectors", contactTitle: "Get in", contactTitleEm: "Touch",
    contactLead: "For any acquisition enquiry, exhibition proposal or gallery partnership.",
    contactL1: "Acquisitions — originals and limited editions",
    contactL2: "Exhibition proposals — France & international",
    contactL3: "Gallery partnerships — by portfolio",
    contactL4: "Press & media — artistic dossier available",
    fFirstname: "First name", fLastname: "Last name", fEmail: "Email",
    fStructure: "Gallery / Institution", fSubject: "Subject", fMessage: "Message",
    fSubmit: "Send enquiry",
    footRights: "© 2024 Kai Krill — All rights reserved",
    footShip: "Works produced and shipped from France",
  }
};

window.KK_CV = [
  { year: "2024 —", entry: "Fondateur, AIDE Fédération",        place: "Statut consultatif ONU" },
  { year: "2024",   entry: "Collection I · Singe — 21 œuvres",  place: "Paris" },
  { year: "2022",   entry: "Cession de sociétés fondées",        place: "Retour à l'art" },
  { year: "2015",   entry: "Fondation de sociétés",              place: "Paris" },
  { year: "2010",   entry: "Directeur Créatif",                  place: "Publicis" },
  { year: "—",      entry: "Bachelor of Arts",                   place: "Middlesex University" },
  { year: "—",      entry: "MANAA",                              place: "École Boulle, Paris" },
];
