window.KK_DATA = {
  works: [
    { id: 1,  title: "Singe I",     src: "img/SINGE/SINGE 1.webp",      status: "sold" },
    { id: 2,  title: "Singe II",    src: "img/SINGE/SINGE 2.webp",      status: "sold" },
    { id: 3,  title: "Singe III",   src: "img/SINGE/SINGE 3.webp",      status: "sold" },
    { id: 4,  title: "Bob",         src: "img/SINGE/SINGE - BOB.webp",  status: "sold" },
    { id: 5,  title: "Singe VII",   src: "img/SINGE/SINGE 7.webp",      status: "sold" },
    { id: 6,  title: "Singe VIII",  src: "img/SINGE/SINGE 8.webp",      status: "sold" },
    { id: 7,  title: "Singe IX",    src: "img/SINGE/SINGE 9.webp",      status: "sold" },
    { id: 8,  title: "Singe X",     src: "img/SINGE/SINGE 10.webp",     status: "sold" },
    { id: 9,  title: "Singe XII",   src: "img/SINGE/SINGE 12.webp",     status: "sold" },
    { id: 10, title: "Singe XIII",  src: "img/SINGE/SINGE 13.webp",     status: "sold" },
    { id: 11, title: "Singe XIV",   src: "img/SINGE/SINGE - 14.webp",   status: "sold" },
    { id: 12, title: "Singe XV",    src: "img/SINGE/SINGE - 15.webp",   status: "sold" },
    { id: 13, title: "Singe XVI",   src: "img/SINGE/SINGE - 16.webp",   status: "sold" },
    { id: 14, title: "Singe XVII",  src: "img/SINGE/SINGE - 17.webp",   status: "sold" },
    { id: 15, title: "Singe XVIII", src: "img/SINGE/SINGE - 18.webp",   status: "sold" },
    { id: 16, title: "Singe XIX",   src: "img/SINGE/SINGE - 19.webp",   status: "sold" },
    { id: 17, title: "Singe XX",    src: "img/SINGE/SINGE - 20.webp",   status: "sold" },
    { id: 18, title: "Singe XXI",   src: "img/SINGE/SINGE - 21.webp",   status: "sold" },
    { id: 19, title: "Tutu",        src: "img/SINGE/SINGE - TUTU.webp", status: "sold" },
    { id: 20, title: "Singe",       src: "img/SINGE/SINGE.webp",        status: "sold" },
  ],
  heroImg:   "img/kai-homepage.webp",
  aboutImg:  "img/back-profil.webp",
  humainImg: "img/HUMAIN/Human 1.webp",
};

window.KK_I18N = {
  fr: {
    navCollection: "Singe", navHumain: "Humain", navAbout: "L'Artiste",
    navEngagement: "Engagement", navPress: "Instagram", btnContact: "Contact Galerie",
    heroEyebrow: "Artiste contemporain · Paris · Depuis 2024",
    heroH1a: "L'encre",
    heroLead: "Après le primate, l'homme. La nouvelle série Humain — premiers regards.",
    heroStat1Label: "Collection II — Nouveau", heroStat1Val: "Humain",
    heroStat2Label: "Collection I", heroStat2Val: "Singe · complète",
    heroStat3Label: "Médium", heroStat3Val: "Encre de Chine",
    heroTag: "Atelier · Paris 2024",
    marquee: "Collection Singe · Encre de Chine · Œuvres originales · Éditions limitées · Art engagé · AIDE Fédération — ONU ·",
    collectionEyebrow: "Collection I — 2024 · Complète", collectionTitle: "Singe",
    collectionMeta: "La série fondatrice. 21 portraits à l'encre de Chine, gestes libres, sans repentir. Le primate comme miroir tendu sur notre condition.",
    sold: "Vendu", worksCaption: "Encre de Chine · Original",
    humainEyebrow: "Collection II — À venir", humainTitle: "Humain",
    humainStatus: "En cours de création",
    humainLead: "Après le primate, l'homme. Une nouvelle série à l'encre — regards qui portent ce que le verbe ne dit pas.",
    humainLeadNew: "Après le primate, l'homme. Une nouvelle série à l'encre — regards qui portent ce que le verbe ne dit pas. Les premières œuvres viennent d'éclore.",
    humainNotify: "Être prévenu·e de la sortie",
    humainDesc: "Une figure qui émerge du geste, portrait à la fois brut et tendu. Le trait refuse la ligne propre — il cherche la vérité du regard.",
    humainEnquire: "Être prévenu·e de la sortie",
    humainView: "Voir l'œuvre",
    humainSerieStatus: "Série à venir · premières œuvres en atelier",
    lblMedium: "Médium", lblFormat: "Format", lblYear: "Année", lblStatus: "Statut",
    statusAvailable: "À venir — 2026",
    originEyebrow: "Origine des visages",
    originLead1: "Chaque visage de la collection",
    originLeadEm: " Humain ",
    originLead2: "est issu d'une mission humanitaire. Les regards sont portés, les traits vus. L'encre ne s'invente pas — elle se rapporte.",
    missionAprMonth: "Avril",
    missionMayotteDesc: "De nombreux visages seront réalisés sur place, au plus près des communautés rencontrées.",
    missionUpcoming: "Prochaine mission",
    singeFootCount: "21 œuvres — intégralement vendues",
    singeFootLink: "Rejoindre la liste des collectionneurs →",
    aboutEyebrow: "L'Artiste", aboutTitle: "Une trajectoire", aboutTitleEm: "hors du commun",
    aboutMeta: "Du Vietnam à Paris, de Publicis à l'encre de Chine — une vie au croisement des humanités.",
    aboutP1: "Né au Vietnam, orphelin, arrivé en France en bas âge. Élevé par plusieurs familles aux traditions plurielles — ivoirienne, musulmane, bouddhiste, chrétienne — Kai Krill a forgé sa vision à l'intersection de toutes les humanités.",
    aboutP2: "Diplômé de l'École Boulle (MANAA) et titulaire d'un Bachelor of Arts de Middlesex University, il exerce d'abord comme Directeur Créatif chez Publicis, avant de créer ses propres sociétés — qu'il revend pour se consacrer entièrement à l'art et à l'action humanitaire.",
    aboutP3: "L'art revient dans sa vie par un défi : dessiner un singe à l'encre de Chine par jour, pendant 30 jours, à la demande de son fils. De ce geste naît une œuvre. De cette œuvre, une mission.",
    quote: "Le primate ne ment pas. Son regard porte ce que l'homme cherche à dissimuler.",
    cvLabel: "Parcours",
    engagementEyebrow: "Engagement", engagementTitle: "L'art comme", engagementTitleEm: "acte d'engagement",
    engagementP1: "Kai Krill reverse 70 % de l'intégralité des fonds générés à l'AIDE Fédération, ONG dotée du statut consultatif auprès des Nations Unies. Chaque œuvre acquise finance directement des projets humanitaires concrets, sur le terrain.",
    engagementP2: "L'esthétique et l'activisme ne s'opposent pas — ils se nourrissent l'un l'autre. Posséder une œuvre de Kai Krill, c'est participer à une action dans le monde réel.",
    impact70Lbl: "des fonds reversés à l'AIDE Fédération, à chaque vente",
    impactUNLbl: "Statut consultatif auprès des Nations Unies",
    impact30Lbl: "Un singe par jour — le geste fondateur",
    impact2Lbl: "Collections — Singe (complète) & Humain (à venir)",
    pressEyebrow: "Mentions",
    contactEyebrow: "Galeries & Collectionneurs", contactTitle: "Prendre", contactTitleEm: "Contact",
    contactLead: "Pour toute demande d'acquisition, proposition d'exposition ou partenariat galerie.",
    contactL1: "Acquisitions — originaux et éditions limitées",
    contactL2: "Propositions d'exposition — France & international",
    contactL3: "Partenariats galerie — demande sur dossier",
    contactL4: "Presse & médias — dossier artistique disponible",
    fFirstname: "Prénom", fLastname: "Nom", fEmail: "Adresse email",
    fStructure: "Structure / Galerie", fSubject: "Nature de la demande", fMessage: "Message",
    fSubmit: "Envoyer la demande",
    footRights: "© 2026 Kai Krill — Tous droits réservés",
    footShip: "Œuvres produites et expédiées depuis la France",
  },
  en: {
    navCollection: "Singe", navHumain: "Human", navAbout: "The Artist",
    navEngagement: "Commitment", navPress: "Instagram", btnContact: "Gallery Enquiries",
    heroEyebrow: "Contemporary artist · Paris · Since 2024",
    heroH1a: "Ink",
    heroLead: "After the primate, man. The new series Human — first gazes.",
    heroStat1Label: "Collection II — New", heroStat1Val: "Human",
    heroStat2Label: "Collection I", heroStat2Val: "Singe · complete",
    heroStat3Label: "Medium", heroStat3Val: "Indian ink",
    heroTag: "Studio · Paris 2024",
    marquee: "Singe Collection · Indian Ink · Original Works · Limited Editions · Engaged Art · AIDE Federation — UN ·",
    collectionEyebrow: "Collection I — 2024 · Complete", collectionTitle: "Singe",
    collectionMeta: "The founding series. 21 portraits in raw Indian ink, free gestures, without repentance. The primate as a mirror held up to our own condition.",
    sold: "Sold", worksCaption: "Indian ink · Original",
    humainEyebrow: "Collection II — Forthcoming", humainTitle: "Human",
    humainStatus: "Work in progress",
    humainLead: "After the primate, man. A new ink series — gazes that carry what words cannot say.",
    humainLeadNew: "After the primate, man. A new ink series — gazes that carry what words cannot say. The first works have just emerged from the studio.",
    humainNotify: "Get notified at release",
    humainDesc: "A figure emerging from the gesture, a portrait both raw and taut. The line refuses to be clean — it seeks the truth of the gaze.",
    humainEnquire: "Get notified at release",
    humainView: "View the work",
    humainSerieStatus: "Series forthcoming · first works in studio",
    lblMedium: "Medium", lblFormat: "Format", lblYear: "Year", lblStatus: "Status",
    statusAvailable: "Forthcoming — 2026",
    originEyebrow: "Origin of the faces",
    originLead1: "Each face in the",
    originLeadEm: " Humain ",
    originLead2: "collection comes from a humanitarian mission. The gazes are lived, the features seen. Ink is not invented — it is reported.",
    missionAprMonth: "April",
    missionMayotteDesc: "Many faces will be created on-site, in close contact with the communities encountered.",
    missionUpcoming: "Next mission",
    singeFootCount: "21 works — entirely sold",
    singeFootLink: "Join the collectors list →",
    aboutEyebrow: "The Artist", aboutTitle: "An uncommon", aboutTitleEm: "trajectory",
    aboutMeta: "From Vietnam to Paris, from Publicis to Indian ink — a life at the crossroads of humanity.",
    aboutP1: "Born in Vietnam, orphaned, arrived in France at a young age. Raised by several families of plural traditions — Ivorian, Muslim, Buddhist, Christian — Kai Krill forged his vision at the intersection of all humanities.",
    aboutP2: "A graduate of École Boulle (MANAA) and holder of a Bachelor of Arts from Middlesex University, he first worked as Creative Director at Publicis before founding his own companies — which he sold to devote himself entirely to art and humanitarian action.",
    aboutP3: "Art returned to his life through a challenge: to draw one monkey in Indian ink every day, for 30 days, at his son's request. From that gesture, a body of work was born. From that work, a mission.",
    quote: "The primate does not lie. Its gaze carries what man seeks to conceal.",
    cvLabel: "Biography",
    engagementEyebrow: "Commitment", engagementTitle: "Art as", engagementTitleEm: "political act",
    engagementP1: "Kai Krill donates 70% of all funds generated to AIDE Fédération, an NGO with consultative status at the United Nations. Each acquired work directly finances concrete humanitarian projects in the field.",
    engagementP2: "Aesthetics and activism do not oppose each other — they feed one another. To own a work by Kai Krill is to participate in an action in the real world.",
    impact70Lbl: "of funds donated to AIDE Fédération, on every sale",
    impactUNLbl: "Consultative status at the United Nations",
    impact30Lbl: "One monkey a day — the founding gesture",
    impact2Lbl: "Collections — Singe (complete) & Human (forthcoming)",
    pressEyebrow: "Mentions",
    contactEyebrow: "Galleries & Collectors", contactTitle: "Get in", contactTitleEm: "Touch",
    contactLead: "For any acquisition enquiry, exhibition proposal or gallery partnership.",
    contactL1: "Acquisitions — originals and limited editions",
    contactL2: "Exhibition proposals — France & international",
    contactL3: "Gallery partnerships — by portfolio",
    contactL4: "Press & media — artistic dossier available",
    fFirstname: "First name", fLastname: "Last name", fEmail: "Email",
    fStructure: "Gallery / Institution", fSubject: "Subject", fMessage: "Message",
    fSubmit: "Send enquiry",
    footRights: "© 2026 Kai Krill — All rights reserved",
    footShip: "Works produced and shipped from France",
  }
};

window.KK_CV = [
  { year: "2026",   entry: "Mission Mayotte — Collection Humain",  place: "Mayotte" },
  { year: "2025 —", entry: "Collection II · Humain — en gestation", place: "Paris" },
  { year: "2024 —", entry: "Fondateur, AIDE Fédération",           place: "Statut consultatif ONU" },
  { year: "2024",   entry: "Collection I · Singe — 21 œuvres",     place: "Paris" },
  { year: "2022",   entry: "Cession de sociétés fondées",           place: "Retour à l'art" },
  { year: "2015",   entry: "Fondation de sociétés",                 place: "Paris" },
  { year: "2010",   entry: "Directeur Créatif",                     place: "Publicis" },
  { year: "—",      entry: "Bachelor of Arts",                      place: "Middlesex University" },
  { year: "—",      entry: "MANAA",                                 place: "École Boulle, Paris" },
];
